# Generated by Django 6.1 on 2026-08-17 21:53

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', validators=[users.validators.validate_image_size], verbose_name='Фото поста'),
        ),
    ]
